### ISSUE TITLE
Dual apt list files

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/codespaces-r2u#2]
_From @eddelbuettel's comment in https://github.com/grantmcdermott/codespaces-r2u/issues/1#issuecomment-1666272339._

Yet we also have the dual list files. Two of these are from your Dockerfile, two of them are not so we may need to have a look at the other scriptlets that run:

```
r$> system("ls -ltr /etc/apt/sources.list.d/")
total 16
-rw-r--r-- 1 root root 129 Aug  4 23:23 cran.list
-rw-r--r-- 1 root root 127 Aug  4 23:23 r2u.list
-rw-r--r-- 1 root root  76 Aug  4 23:24 cran-ubuntu.list
-rw-r--r-- 1 root root  65 Aug  4 23:24 cranapt.list
```

**Comment by eddelbuettel** [comment]
The first two are you (using my r2u setup).  The other two maybe from devcontainers also enabling r2u?

https://github.com/grantmcdermott/codespaces-r2u/blob/141d95f5aef83662658a01b5c0ac1be4bd14c980/.devcontainer/Dockerfile#L24-L32

**Comment by grantmcdermott** [comment]
Ah, good catch. Yes, I believe the [r-apt](https://github.com/rocker-org/devcontainer-features/blob/main/src/r-apt/README.md) feature that I am using [here](https://github.com/grantmcdermott/codespaces-r2u/blob/main/.devcontainer/devcontainer.json#L8) also calls in r2u. (@eitsupi can you confirm?) So, it's likely redundancy on my side. I need to head out but will take a closer look over the weekend.

**Comment by eitsupi** [comment]
Yes, there is absolutely no need to write a Dockerfile to use r2u. Look at this for example.
https://github.com/microsoft/datascience-py-r/blob/e7372c78dbc6d0c59e6d9d32299d0b8d1c44e9ac/src/datascience-py-r/.devcontainer/devcontainer.json

However, the bspm configuration must be done after installing R yourself for now, so you must use `postCreateCommand`, etc.

I have opened a PR to add an option to do this with the r-apt Feature. rocker-org/devcontainer-features#169

**Comment by grantmcdermott** [comment]
Closed in https://github.com/grantmcdermott/codespaces-r2u/commit/7bbe63ac777ca8ad84f186f5329211187b8659d4
